# Generated by Django 4.1.7 on 2023-02-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'связь', 'verbose_name_plural': 'Редактирование статьи'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'раздел', 'verbose_name_plural': 'Создать раздел'},
        ),
    ]
